### ISSUE TITLE
NameError: global name 'settings' is not defined

### ISSUE THREAD

**Issue by mandx** [jisaacks/GitGutter#141]
I'm getting the error `NameError: global name 'settings' is not defined` in ST3's console, and the exception is thrown at `~/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 73, in settings_loaded` which I think is this line: [git_gutter_events.py:L73](https://github.com/jisaacks/GitGutter/blob/master/git_gutter_events.py#L73). The plugin works, anyway.

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 255, in on_post_save
    callback.on_post_save(v)
  File "git_gutter_events in ~/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 29, in on_post_save
  File "git_gutter_events in ~/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 73, in settings_loaded
NameError: global name 'settings' is not defined
```

I'm using OSX 10.9 and ST3 build 3059.

**Comment by rchl** [comment]
Unlikely to still be a problem after 3 years and many changed. Closing.
