### ISSUE TITLE
Error when loading GitGutter with ST3 on Linux

### ISSUE THREAD

**Issue by cloudhead** [jisaacks/GitGutter#150]
Looking at the console, I see:

```
GitGutter now comparing against: HEAD
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 526, in run_
    return self.run()
  File "git_gutter_compare in /home/cloudhead/.config/sublime-text-3/Installed Packages/GitGutter.sublime-package", line 15, in run
  File "git_gutter_compare in /home/cloudhead/.config/sublime-text-3/Installed Packages/GitGutter.sublime-package", line 38, in commit_list
  File "git_gutter_compare in /home/cloudhead/.config/sublime-text-3/Installed Packages/GitGutter.sublime-package", line 38, in <listcomp>
  File "git_gutter_compare in /home/cloudhead/.config/sublime-text-3/Installed Packages/GitGutter.sublime-package", line 43, in parse_result
IndexError: list index out of range
```

**Comment by rchl** [comment]
Very old report and probably doesn't happen anymore to you so will close. Please report new bug if you manager to reproduce. :)
