### ISSUE TITLE
GitGutter fails to run due to PermissionError 

### ISSUE THREAD

**Issue by jasonsims** [jisaacks/GitGutter#178]
Recently, gitgutter started failing for me and is showing the traceback below in the console. It was working so I'm not sure what happened. Does anyone what gitgutter is trying to access here but can't? 

I'm using:
Sublime Text 3 Build 3059
GitGutter stable installed through package control

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 526, in run_
    return self.run()
  File "git_gutter in /Users/jasonsims/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 45, in run
  File "view_collection in /Users/jasonsims/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 51, in diff
  File "git_gutter_handler in /Users/jasonsims/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 153, in diff
  File "git_gutter_handler in /Users/jasonsims/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 233, in run_command
  File "X/subprocess.py", line 818, in __init__
  File "X/subprocess.py", line 1416, in _execute_child
PermissionError: [Errno 13] Permission denied
```

**Comment by andreasb** [comment]
@jisaacks I'm getting the `PermissionError` too:

```python
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 526, in run_
    return self.run()
  File "git_gutter in /Users/andreas/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 45, in run
  File "view_collection in /Users/andreas/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 51, in diff
  File "git_gutter_handler in /Users/andreas/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 153, in diff
  File "git_gutter_handler in /Users/andreas/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 233, in run_command
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
PermissionError: [Errno 13] Permission denied
```

How do I print the args? `GitGutter.sublime-package` seems to be a binary file?

**Comment by andreasb** [comment]
Ah, that fixed it. Thanks @jasonsims, I appreciate it.

**Comment by jisaacks** [comment]
@andreasb if your issue is solved can you close this issue?

**Comment by andreasb** [comment]
It doesn't seem like I have the power to do so. :-/

**Comment by jasonsims** [comment]
This was originally my issue so I'll go ahead and close it. The resolution is detailed in [issuecomment-72684981](https://github.com/jisaacks/GitGutter/issues/178#issuecomment-72684981)

**Comment by jisaacks** [comment]
@jasonsims right, was on my phone and didn't notice. Thanks!
