### ISSUE TITLE
GitGutter stopped working on ST3 OS X

### ISSUE THREAD

**Issue by jhuckaby** [jisaacks/GitGutter#188]
Hello,

I noticed that my GitGutter has suddenly stopped working.  I tried reinstalling it via Package Manager, and on the command-line, to no avail.  I found this in the console (repeated lots of times):

```text
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 526, in run_
    return self.run()
  File "/Users/jhuckaby/Library/Application Support/Sublime Text 3/Packages/GitGutter/git_gutter.py", line 24, in run
    if ViewCollection.untracked(self.view):
  File "/Users/jhuckaby/Library/Application Support/Sublime Text 3/Packages/GitGutter/view_collection.py", line 56, in untracked
    return ViewCollection.views[key].untracked()
KeyError: '/Users/jhuckaby/git/Mirror-Bot/lib/Mirror.pm'
```

Any ideas?  What is a "KeyError"?

GitGutter is the only package I have installed (except for PackageManager).

Sublime Text 3 Build 3065
OS X 10.8.5

**Comment by bfred-it** [comment]
Could be an issue with PATH? It wasn't working for me until I installed [SublimeFixMacPath](https://github.com/int3h/SublimeFixMacPath) on my ST 3 / OSX 10.10.1:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 526, in run_
    return self.run()
  File "git_gutter in /[...]/GitGutter.sublime-package", line 45, in run
  File "view_collection in /[...]/GitGutter.sublime-package", line 51, in diff
  File "git_gutter_handler in /[...]/GitGutter.sublime-package", line 153, in diff
  File "git_gutter_handler in /[...]/GitGutter.sublime-package", line 233, in run_command
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
```

**Comment by jisaacks** [comment]
Is this still an issue?

**Comment by jhuckaby** [comment]
Seems to work for me now, thanks!  OS X 10.10.3, ST3 Build 3083, GitGutter Commit #205f73bffc56dc2afddf921b6cf1de44b0dca073 (Apr 22).
