### ISSUE TITLE
Not working on OSX 10.9.5 for ST3

### ISSUE THREAD

**Issue by OlivierCuyp** [jisaacks/GitGutter#192]
Since the last patch OSX patch (version: 10.9.5) gitgutter is not working anymore.
Here are the logs from the console:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 526, in run_
    return self.run()
  File "git_gutter_compare in /Users/olivier/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 15, in run
  File "git_gutter_compare in /Users/olivier/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 38, in commit_list
  File "git_gutter_compare in /Users/olivier/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 38, in <listcomp>
  File "git_gutter_compare in /Users/olivier/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 43, in parse_result
IndexError: list index out of range
reloading Packages/User/SublimeLinter.sublime-settings
Writing file /Users/olivier/Projects/wooking/src/server.js with encoding UTF-8 (atomic)
Writing file /Users/olivier/Projects/wooking/src/server.js with encoding UTF-8 (atomic)
Unable to open /Users/olivier/Library/Application Support/Sublime Text 3/Packages/User/GitGutter.sublime-settings
Unable to open /Users/olivier/Library/Application Support/Sublime Text 3/Packages/GitGutter/GitGutter.sublime-settings

**Comment by devotis** [comment]
@grena Wow, nice find. My ST3 editor stopped showing the git gutter at some point. I'm on OSX 10.10.5. 
So I started ST3 from the command line, like you said. And I saw the git gutter again.

However I want to have the git gutter too when I launch Sublime from the Dock. This solution fixed that: https://github.com/jisaacks/GitGutter/issues/215#issuecomment-85133123
