### ISSUE TITLE
Gitgutter icons not showing after updating to MAC OS X Yosemite

### ISSUE THREAD

**Issue by lauriegao** [jisaacks/GitGutter#207]
My Gitgutter icons won't display after updating to Yosemite recently.

I am using Sublme Text 2.  I tried uninstalling and reinstalling Gitgutter through Package Control and Git with no luck. 

Found this repeated three times in console every time I save changes.

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 339, in run_
  File "./git_gutter.py", line 33, in run
  File "./view_collection.py", line 50, in diff
  File "./git_gutter_handler.py", line 156, in diff
  File "./git_gutter_handler.py", line 248, in run_command
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 623, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 1141, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Comment by jisaacks** [comment]
Have you tried using `git` in the terminal since you upgraded? I think there was an issue where Yosemite upgraded git and you need to accept the terms before you can use it.

**Comment by lauriegao** [comment]
Yeah, I did. Git works fine in the terminal.

**Comment by jisaacks** [comment]
Did you try setting the [git path](https://github.com/jisaacks/GitGutter#git-path)?

**Comment by lauriegao** [comment]
Yes, fixed with setting the [git path] (https://github.com/jisaacks/GitGutter#git-path).
Thank you!

**Comment by jisaacks** [comment]
OK I am going to close this issue then. Glad you got it working :+1:

**Comment by coderbydesign** [comment]
Had a similar issue after upgrading version of git. Everything worked except the icons in the gutter. Explicitly setting the [git path](https://github.com/jisaacks/GitGutter#git-path) fixed the issue!
