### ISSUE TITLE
'GitGutterHandler' object has no attribute 'git_dir'

### ISSUE THREAD

**Issue by fiznool** [jisaacks/GitGutter#212]
When trying to use GitGutter this morning, I find this printed to the console:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 526, in run_
    return self.run()
  File "git_gutter_compare in /home/fiznool/.config/sublime-text-3/Installed Packages/GitGutter.sublime-package", line 15, in run
  File "git_gutter_compare in /home/fiznool/.config/sublime-text-3/Installed Packages/GitGutter.sublime-package", line 20, in commit_list
  File "git_gutter_handler in /home/fiznool/.config/sublime-text-3/Installed Packages/GitGutter.sublime-package", line 193, in git_commits
AttributeError: 'GitGutterHandler' object has no attribute 'git_dir'
```

This happens when I try to run any of the GitGutter 'compare to' commands from the command palette. I'm really not sure what has changed since the last time I used GitGutter, I can't really think of anything.

GitGutter v1.1.1
ST3 build 3065
Ubuntu 14.10

**Comment by fiznool** [comment]
Seems to have now sorted itself out. No idea what happened!
