### ISSUE TITLE
Running into an issue with this on Windows

### ISSUE THREAD

**Issue by m0ngr31** [jisaacks/GitGutter#223]
Been using this package on Linux for a while, but just tried it in Windows 8.1 and I'm running into an issue that's breaking it.

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 535, in run_
    return self.run()
  File "git_gutter in C:\Users\Joe\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package", line 33, in run
  File "view_collection in C:\Users\Joe\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package", line 51, in diff
  File "git_gutter_handler in C:\Users\Joe\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package", line 156, in diff
  File "git_gutter_handler in C:\Users\Joe\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package", line 248, in run_command
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "./subprocess.py", line 1112, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

There are about a million of those every time I edit a file. Any ideas?

**Comment by ottopoika** [comment]
Same issue here. Has worked fine before.

**Comment by ottopoika** [comment]
@m0ngr31 It seems that you might need to set git_binary path in GitGutter settings. In windows you get the path with where-command (same as which in linux).

**Comment by m0ngr31** [comment]
@ottopoika, yeah it was a path issue. I was running my console program as administrator and it was on that PATH, just not on my local user path that Sublime was checking. Thanks.
