### ISSUE TITLE
Invalid handle

### ISSUE THREAD

**Issue by FichteFoll** [jisaacks/GitGutter#227]
Today I noticed that I get the following exception whenever GitGutter is run (i.e. any action on a version controlled file):

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 535, in run_
    return self.run()
  File "git_gutter in C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package", line 33, in run
  File "view_collection in C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package", line 51, in diff
  File "git_gutter_handler in C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package", line 156, in diff
  File "git_gutter_handler in C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package", line 248, in run_command
  File "./subprocess.py", line 789, in __init__
    warnings.warn("pass_fds overriding close_fds.", RuntimeWarning)
  File "./subprocess.py", line 988, in _get_handles
    if mswindows:
  File "./subprocess.py", line 1038, in _make_inheritable
    
OSError: [WinError 6] Das Handle ist ungültig
```

(Error translates to: "The handle is invalid")

**Comment by FichteFoll** [comment]
Seems to have been a Sublime Text issue that occured with all processes spawned using subprocess. I couldn't run build systems either.

Restart fixed it.

**Comment by jisaacks** [comment]
Ahh. Gotcha.
