### ISSUE TITLE
Doesn't run in Windows 7 ST2

### ISSUE THREAD

**Issue by fatdollar** [jisaacks/GitGutter#244]
I just installed this today.  I've added my "git_binary" path to my settings and added the color fields to my color scheme.  I'm not seeing anything for any modified files.

A look at the console shows that there is a problem finding a file somewhere. 

```
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 339, in run_
  File ".\git_gutter.py", line 32, in run
  File ".\view_collection.py", line 55, in untracked
  File ".\git_gutter_handler.py", line 180, in untracked
  File ".\git_gutter_handler.py", line 196, in handle_files
  File ".\git_gutter_handler.py", line 261, in run_command
  File ".\subprocess.py", line 633, in __init__
  File ".\subprocess.py", line 842, in _execute_child
WindowsError: [Error 2] The system cannot find the file specified
```

I've tried looking for subprocess.py but can't find it.  Any suggestions?

I've tried a few projects with the same result.  The console also shows where GitGutter loaded with no issues and I'm able to see GitGutter in the Command Palette and in the menus.

**Comment by Zooce** [comment]
I'm getting a similar issue:

```
Traceback (most recent call last):
  File "e:\devtools\sublimetext3\sublime_plugin.py", line 553, in run_
    return self.run()
  File "git_gutter in e:\devtools\sublimetext3\Data\Installed Packages\GitGutter.sublime-package", line 34, in run
  File "view_collection in e:\devtools\sublimetext3\Data\Installed Packages\GitGutter.sublime-package", line 55, in untracked
  File "git_gutter_handler in e:\devtools\sublimetext3\Data\Installed Packages\GitGutter.sublime-package", line 180, in untracked
  File "git_gutter_handler in e:\devtools\sublimetext3\Data\Installed Packages\GitGutter.sublime-package", line 196, in handle_files
  File "git_gutter_handler in e:\devtools\sublimetext3\Data\Installed Packages\GitGutter.sublime-package", line 261, in run_command
  File "./subprocess.py", line 789, in __init__
  File "./subprocess.py", line 988, in _get_handles
  File "./subprocess.py", line 1038, in _make_inheritable
OSError: [WinError 6] The handle is invalid
```

**Comment by sigod** [comment]
@fatdollar @Zooce 

Edit `git_binary` in GitGutter's settings.

I've just tried to make my `git_binary` incorrect and that's what I see now in logs:

	Traceback (most recent call last):
	  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 553, in run_
	    return self.run()
	  File "git_gutter in C:\Users\sigod\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package", line 34, in run
	  File "view_collection in C:\Users\sigod\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package", line 55, in untracked
	  File "git_gutter_handler in C:\Users\sigod\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package", line 180, in untracked
	  File "git_gutter_handler in C:\Users\sigod\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package", line 196, in handle_files
	  File "git_gutter_handler in C:\Users\sigod\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package", line 261, in run_command
	  File "./subprocess.py", line 824, in __init__
	  File "./subprocess.py", line 1118, in _execute_child
	FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by Zooce** [comment]
@sigod, I've tried the following directories for `git_binary` including:

```
C:\Program Files (x86)\Git\bin\git.exe
/bin/git.exe
```

**Comment by sigod** [comment]
@Zooce You need to escape backslash. Try `C:\\Program Files (x86)\\Git\\bin\\git.exe`.

**Comment by Zooce** [comment]
@sigod, yes I know. I just didn't show that in the last comment.

**Comment by sigod** [comment]
@Zooce Then maybe you have x64 version of Git?

**Comment by Zooce** [comment]
@sigod 

```
$ git --version
git version 1.9.5.msysgit.0
```

**Comment by fatdollar** [comment]
I can tell you I'm running the x86 version for sure.

**Comment by sigod** [comment]
@Zooce, try `C:\\Program Files\\Git\\bin\\git.exe`. Though, you previous comment tells me it probably won't help.

Try to update Git as a last resort.

**Comment by Zooce** [comment]
@sigod, same error. Unfortunately, this is my work machine, so I can't just upgrade git. If that's the case, am I SOL?

**Comment by sigod** [comment]
@Zooce, looks like you are... Though, if it's work machine you can ask admins for help.

**Comment by fatdollar** [comment]
I'm not sure why mine started working but I put the path in both the default and the user settings files.

**Comment by fatdollar** [comment]
As an update.  I decided to try this out on my laptop to confirm that this was consistently working.

I installed GitGutter added the binary path to both Default and User settings files for Git Gutter and then added the color scheme definitions to my current color scheme.  After restarting sublime text Git Gutter is functioning perfectly.

Again I'm not sure what changed other than I put the binary in the in both locations but I have confirmed that this is no longer an issue for me.

**Comment by Zooce** [comment]
@fatdollar, how do you modify the Default settings?

**Comment by fatdollar** [comment]
Preferences->Package Settings->GitGutter you should see 2 options at that point
Settings-Default
Settings-User

**Comment by Zooce** [comment]
Right, but I can't edit it...

**Comment by fatdollar** [comment]
My thoughts are at this point that somehow your file is read-only or that you don't have the correct privileges to edit it.  This is possible if you are using a work computer like you say.  The file is located in the AppData folder and I'm not sure if you would need special privileges to edit this.

**Comment by Zooce** [comment]
I have the portable version of sublime text, so maybe that's it..

**Comment by fatdollar** [comment]
Possibly.  I'll pull down the portable version and see if I can get that one working as well.

**Comment by fatdollar** [comment]
I downloaded the portable version and went through the same steps ad I mentioned above and everything is working for me.

I feel like an idiot now:  I just looked at your traceback and noticed that your path has sublimetext3 in it.  I've been doing all of this in sublime text 2 and I'm not sure that this package is supported in sublime text 3.  The collaborators would have to confirm that. But I think if you used 2 instead of 3 you would see it start working.

**Comment by Zooce** [comment]
Okay, so I got it to work. The problem is that I open sublime text via `subl` from git bash, and when I do this, for some reason it doesn't work (https://forum.sublimetext.com/t/build-system-the-handle-is-invalid/1764/3). When I opened the exe directly (double clicking the exe), it worked.

IMHO, I think this is just a workaround...

**Comment by fatdollar** [comment]
Ah interesting.  I think it should be working via command line or not.  So you are able to use this with sublime text 3?

**Comment by Zooce** [comment]
Yes, sublime text 3

**Comment by fatdollar** [comment]
That's good to know.

**Comment by sigod** [comment]
> The problem is that I open sublime text via `subl` from git bash

Works for me.

**Comment by sigod** [comment]
> I've been doing all of this in sublime text 2 and I'm not sure that this package is supported in sublime text 3. The collaborators would have to confirm that.

This package supports both, ST2 and ST3, versions. Though, I haven't used ST2 for a long time.

**Comment by mscarchilli** [comment]
@sigod This fixed it for me. I was having this issue on Sublime Text 3 Build 3126 when I first noticed the problem, not sure if it's related or if my GitGutter had been updated recently. Either way, updating the "git_binary" did the trick. Thank you!

> @Zooce, try C:\\Program Files\\Git\\bin\\git.exe. Though, you previous comment tells me it probably won't help.
>
> Try to update Git as a last resort.

Changed from this
```
{
  "git_binary": "C:\\Program Files (x86)\\Git\\bin\\git.exe",
  "show_markers_on_untracked_file": true
}
```

To this
```
{
  "git_binary": "C:\\Program Files\\Git\\bin\\git.exe",
  "show_markers_on_untracked_file": true
}
```

**Comment by deathaxe** [comment]
As from V1.4.0 GitGutter uses the `PATH` environment variable to lookup the git binary. Therefore `git_binary` setting is required for portable setups only or if the git can't be found/defined in the `PATH` for some reason.
