### ISSUE TITLE
GitGutter just stopped working - OSX, ST3

### ISSUE THREAD

**Issue by tomatau** [jisaacks/GitGutter#252]
Have tried removing and installing again.
Git is definitely in my path as I use it from my iTerm all the time.
Using bracket highlighter too and that is still showing icons in the gutter... just nothing from gitgutter.
Also tried GitGutter-Edge, still no cigar :(
Any help really appreciated as this plugin is wayyy good!

Getting this error:
```
Traceback (most recent call last):
  File "git_gutter_events in /Users/tomatao/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 74, in callback
  File "view_collection in /Users/tomatao/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 20, in add
AttributeError: 'NoneType' object has no attribute 'views'
```

**Comment by baudehlo** [comment]
Check to see if you need to re-accept your xcode license.
```
sudo xcodebuild -license
```
Happened to me and that fixed it.

**Comment by tomatau** [comment]
Yep worked, thanks.

**Comment by atuttle** [comment]
Fix worked for me too.

**Comment by Memory-Yuan** [comment]
Thanks

**Comment by baudehlo** [comment]
Looks like this issue can be closed.

For Google: SublimeGit stopped working because of the same issue.
