### ISSUE TITLE
OSError: [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by csitarichie** [jisaacks/GitGutter#275]
Traceback (most recent call last):
  File "c:\repos\commonapi_mgc_tools\sublime_text_bin\sublime_plugin.py", line 553, in run_
    return self.run()
  File "git_gutter in c:\repos\commonapi_mgc_tools\sublime_text_bin\Data\Installed Packages\GitGutter.sublime-package", line 34, in run
  File "view_collection in c:\repos\commonapi_mgc_tools\sublime_text_bin\Data\Installed Packages\GitGutter.sublime-package", line 55, in untracked
  File "git_gutter_handler in c:\repos\commonapi_mgc_tools\sublime_text_bin\Data\Installed Packages\GitGutter.sublime-package", line 180, in untracked
  File "git_gutter_handler in c:\repos\commonapi_mgc_tools\sublime_text_bin\Data\Installed Packages\GitGutter.sublime-package", line 196, in handle_files
  File "git_gutter_handler in c:\repos\commonapi_mgc_tools\sublime_text_bin\Data\Installed Packages\GitGutter.sublime-package", line 261, in run_command
  File "./subprocess.py", line 789, in **init**
  File "./subprocess.py", line 988, in _get_handles
  File "./subprocess.py", line 1038, in _make_inheritable

**Comment by Zooce** [comment]
```
Traceback (most recent call last):
  File "e:\devtools\Sublime_Text_3_Dev\sublime_plugin.py", line 797, in run_
    return self.run()
  File "git_gutter in e:\devtools\Sublime_Text_3_Dev\Data\Installed Packages\GitGutter.sublime-package", line 34, in run
  File "view_collection in e:\devtools\Sublime_Text_3_Dev\Data\Installed Packages\GitGutter.sublime-package", line 59, in untracked
  File "git_gutter_handler in e:\devtools\Sublime_Text_3_Dev\Data\Installed Packages\GitGutter.sublime-package", line 266, in untracked
  File "git_gutter_handler in e:\devtools\Sublime_Text_3_Dev\Data\Installed Packages\GitGutter.sublime-package", line 282, in handle_files
  File "git_gutter_handler in e:\devtools\Sublime_Text_3_Dev\Data\Installed Packages\GitGutter.sublime-package", line 347, in run_command
  File "./python3.3/subprocess.py", line 784, in __init__
  File "./python3.3/subprocess.py", line 980, in _get_handles
  File "./python3.3/subprocess.py", line 1030, in _make_inheritable
OSError: [WinError 6] The handle is invalid
```
