### ISSUE TITLE
GitGutter stopped working right after upgrade

### ISSUE THREAD

**Issue by hamidnazari** [jisaacks/GitGutter#298]
Had to downgrade to 1.2.2 to make it work again.

Error log from after upgrade:
```
Traceback (most recent call last):
  File "./git_gutter_events.py", line 74, in callback
  File "./view_collection.py", line 20, in add
  File "./git_gutter_handler.py", line 20, in __init__
  File "./git_gutter_handler.py", line 285, in load_settings
AttributeError: 'module' object has no attribute 'which'
Traceback (most recent call last):
  File "./git_gutter_events.py", line 74, in callback
  File "./view_collection.py", line 20, in add
  File "./git_gutter_handler.py", line 20, in __init__
  File "./git_gutter_handler.py", line 285, in load_settings
AttributeError: 'module' object has no attribute 'which'
Traceback (most recent call last):
  File "./git_gutter_events.py", line 74, in callback
  File "./view_collection.py", line 20, in add
  File "./git_gutter_handler.py", line 20, in __init__
  File "./git_gutter_handler.py", line 285, in load_settings
AttributeError: 'module' object has no attribute 'which'
Traceback (most recent call last):
  File "./git_gutter_events.py", line 74, in callback
  File "./view_collection.py", line 20, in add
  File "./git_gutter_handler.py", line 20, in __init__
  File "./git_gutter_handler.py", line 285, in load_settings
AttributeError: 'module' object has no attribute 'which'
Traceback (most recent call last):
  File "./git_gutter_events.py", line 74, in callback
  File "./view_collection.py", line 20, in add
  File "./git_gutter_handler.py", line 20, in __init__
  File "./git_gutter_handler.py", line 285, in load_settings
AttributeError: 'module' object has no attribute 'which'
Traceback (most recent call last):
  File "./git_gutter_events.py", line 74, in callback
  File "./view_collection.py", line 20, in add
  File "./git_gutter_handler.py", line 20, in __init__
  File "./git_gutter_handler.py", line 285, in load_settings
AttributeError: 'module' object has no attribute 'which'
Traceback (most recent call last):
  File "./git_gutter_events.py", line 74, in callback
  File "./view_collection.py", line 20, in add
  File "./git_gutter_handler.py", line 20, in __init__
  File "./git_gutter_handler.py", line 285, in load_settings
AttributeError: 'module' object has no attribute 'which'
Package Control: Skipping automatic upgrade, last run at 2016-08-15 16:15:01, next run at 2016-08-15 17:15:01 or after
Traceback (most recent call last):
  File "./git_gutter_events.py", line 74, in callback
  File "./view_collection.py", line 20, in add
  File "./git_gutter_handler.py", line 20, in __init__
  File "./git_gutter_handler.py", line 285, in load_settings
AttributeError: 'module' object has no attribute 'which'
Traceback (most recent call last):
  File "./git_gutter_events.py", line 74, in callback
  File "./view_collection.py", line 20, in add
  File "./git_gutter_handler.py", line 20, in __init__
  File "./git_gutter_handler.py", line 285, in load_settings
AttributeError: 'module' object has no attribute 'which'
Traceback (most recent call last):
  File "./git_gutter_events.py", line 74, in callback
  File "./view_collection.py", line 20, in add
  File "./git_gutter_handler.py", line 20, in __init__
  File "./git_gutter_handler.py", line 285, in load_settings
AttributeError: 'module' object has no attribute 'which'
```

**Comment by sigod** [comment]
Works for me. What's your OS?

**Comment by jisaacks** [comment]
@hamidnazari did you restart sublime after upgrading?

**Comment by hamidnazari** [comment]
I sure did. It's a machine running Fedora that I don't have access to at the moment. I'll try to gather more info tomorrow. I'll find out what Python version my Sublime runs, probably not 3.3 since it's complaining about `shutil.which`.

**Comment by hamidnazari** [comment]
Turns out I'm running a somewhat old version of Sublime Text 2 packed with Python 2.6.6.

![image](https://cloud.githubusercontent.com/assets/544028/17683406/f28f5966-6395-11e6-9c7a-d1902fd89753.png)

```
>>> sys.version_info
(2, 6, 6, 'final', 0)
```

I'm going to upgrade Sublime on my end. Feel free to close this ticket if you're willing to drop support below [build 3006](https://www.sublimetext.com/3).
