### ISSUE TITLE
ImportError: No module named 'view_collection'

### ISSUE THREAD

**Issue by smanolloff** [jisaacks/GitGutter#330]
Hi, after the last update (just a minute ago), I am getting the below error:

```
reloading plugin GitGutter.git_gutter
Traceback (most recent call last):
  File "/Users/simo/Library/Application Support/Sublime Text 3/Packages/GitGutter/git_gutter.py", line 6, in <module>
    from .view_collection import ViewCollection
ImportError: No module named 'GitGutter.view_collection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/simo/Library/Application Support/Sublime Text 3/Packages/GitGutter/git_gutter.py", line 8, in <module>
    from view_collection import ViewCollection
ImportError: No module named 'view_collection'
```

GitGutter 1.4.0, Sublime build 3126

**Comment by r-stein** [comment]
Have you tried to restart Sublime Text?

**Comment by smanolloff** [comment]
Yes, it was the first thing I did, did not help :(

**Comment by r-stein** [comment]
Have you modified the git_gutter file in the past?

**Comment by rchl** [comment]
It doesn't look like Sublime was restarted really. Maybe restart the computer just to be sure.

**Comment by rchl** [comment]
Actually it looks like you have the package extracted in the packages directory. Normally it installs to `Installed Packages/GitGutter.sublime-package` so you might have two installations of git gutter running simultaneously or something weird like that.

Tried removing the existing one (using Package Control or manually - whatever works), and install it again.

**Comment by smanolloff** [comment]
splendid!
