### ISSUE TITLE
Diff Popup stopped working

### ISSUE THREAD

**Issue by dotKev** [jisaacks/GitGutter#335]
The diff gutter markings are working correctly but the popup box has stopped working.
I am on Sublime build 3125 and GitGutter-Edge v2016.11.17.13.12.07

When hovering over the gutter on a changed line, I get this in the console:
```python
Traceback (most recent call last):
  File "git_gutter_handler in /Users/***/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter-Edge.sublime-package", line 376, in <lambda>
  File "git_gutter_handler in /Users/***/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter-Edge.sublime-package", line 372, in read_output
  File "promise in /Users/***/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter-Edge.sublime-package", line 126, in resolve_fn
  File "promise in /Users/***/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter-Edge.sublime-package", line 138, in _do_resolve
  File "promise in /Users/***/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter-Edge.sublime-package", line 104, in callback_wrapper
  File "promise in /Users/***/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter-Edge.sublime-package", line 126, in resolve_fn
  File "promise in /Users/***/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter-Edge.sublime-package", line 138, in _do_resolve
  File "promise in /Users/***/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter-Edge.sublime-package", line 98, in callback_wrapper
  File "promise in /Users/***/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter-Edge.sublime-package", line 126, in resolve_fn
  File "promise in /Users/***/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter-Edge.sublime-package", line 138, in _do_resolve
  File "promise in /Users/***/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter-Edge.sublime-package", line 104, in callback_wrapper
  File "promise in /Users/***/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter-Edge.sublime-package", line 126, in resolve_fn
  File "promise in /Users/***/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter-Edge.sublime-package", line 138, in _do_resolve
  File "promise in /Users/***/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter-Edge.sublime-package", line 98, in callback_wrapper
  File "git_gutter_popup in /Users/***/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter-Edge.sublime-package", line 207, in _show_diff_popup_impl
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found
```

**Comment by r-stein** [comment]
Oh yeah there is a version in which the folder is called GitGutter-Edge. We currently load the popup css from `"Packages/GitGutter/gitgutter_popup.css"`. I am not sure, which is the best way to substitue GitGutter wie the corresponding folder.

**Comment by deathaxe** [comment]
```python
sublime.find_resources("gitgutter_popup.css")
```

**Comment by r-stein** [comment]
@deathaxe Ah thanks =)
