### ISSUE TITLE
OSError: [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by Zooce** [jisaacks/GitGutter#357]
Getting the following error in Sublime Text 3 (dev build), on Windows 7 x64:

```
Traceback (most recent call last):
  File "git_gutter_handler in e:\devtools\Sublime_Text_3_Dev\Data\Installed Packages\GitGutter.sublime-package", line 376, in <lambda>
  File "git_gutter_handler in e:\devtools\Sublime_Text_3_Dev\Data\Installed Packages\GitGutter.sublime-package", line 370, in read_output
  File "./python3.3/subprocess.py", line 784, in __init__
  File "./python3.3/subprocess.py", line 980, in _get_handles
  File "./python3.3/subprocess.py", line 1030, in _make_inheritable
OSError: [WinError 6] The handle is invalid
```

**Comment by deathaxe** [comment]
From the traceback I guess you are running GitGutter 1.4.0?

If so, this issue is caused by a python bug on Windows. A workaround will come with next release. If you are interested in testing this bugfix, you may install GitGutter-Edge.

**Comment by Zooce** [comment]
I just installed GitGutter-Edge, and nothing is actually happening at all now. I tried to open the settings and got the following errors:
```
Unable to open /e/devtools/Sublime_Text_3_Dev/Data/Packages/GitGutter/GitGutter.sublime-settings
Unable to open /e/devtools/Sublime_Text_3_Dev/Data/Packages/User/GitGutter.sublime-settings
```

**Comment by Zooce** [comment]
Things seem to be working at the moment, but what's concerning is that I have no idea why...I suppose this issue can be closed unless someone things there's some other underlying issue here.
