### ISSUE TITLE
Leaking file descriptors?

### ISSUE THREAD

**Issue by rwols** [jisaacks/GitGutter#384]
It looks like gitgutter is opening temp files like crazy and not closing them. Here is a snippet of my console log in Sublime:

```python console
GitGutter failed to run git: [Errno 24] Too many open files
GitGutter failed to run git: [Errno 24] Too many open files
GitGutter failed to run git: [Errno 24] Too many open files
GitGutter failed to run git: [Errno 24] Too many open files
GitGutter failed to run git: [Errno 24] Too many open files
GitGutter failed to run git: [Errno 24] Too many open files
GitGutter failed to run git: [Errno 24] Too many open files
GitGutter failed to run git: [Errno 24] Too many open files
Traceback (most recent call last):
  File "git_gutter_handler in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 653, in <lambda>
  File "git_gutter_handler in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 650, in read_output
  File "modules.promise in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 127, in resolve_fn
  File "modules.promise in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 139, in _do_resolve
  File "modules.promise in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 97, in callback_wrapper
  File "git_gutter_handler in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 276, in write_file
  File "git_gutter_handler in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 83, in tmp_file
  File "./python3.3/tempfile.py", line 290, in mkstemp
  File "./python3.3/tempfile.py", line 219, in _mkstemp_inner
OSError: [Errno 24] Too many open files: '/var/folders/fc/w04z5z256yv_gm0tl5qx3mw00000gq/T/git_gutter_5kyq1w'
GitGutter failed to run git: [Errno 24] Too many open files
GitGutter failed to run git: [Errno 24] Too many open files
Traceback (most recent call last):
  File "git_gutter_handler in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 653, in <lambda>
  File "git_gutter_handler in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 650, in read_output
  File "modules.promise in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 127, in resolve_fn
  File "modules.promise in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 139, in _do_resolve
  File "modules.promise in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 97, in callback_wrapper
  File "git_gutter_handler in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 276, in write_file
  File "git_gutter_handler in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 83, in tmp_file
  File "./python3.3/tempfile.py", line 290, in mkstemp
  File "./python3.3/tempfile.py", line 219, in _mkstemp_inner
OSError: [Errno 24] Too many open files: '/var/folders/fc/w04z5z256yv_gm0tl5qx3mw00000gq/T/git_gutter__hxtk1'
OSError [Errno 24] Too many open files
OSError [Errno 24] Too many open files
error: Too many open files
error: Too many open files
GitGutter failed to run git: [Errno 24] Too many open files
GitGutter failed to run git: [Errno 24] Too many open files
Traceback (most recent call last):
  File "git_gutter_handler in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 653, in <lambda>
  File "git_gutter_handler in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 650, in read_output
  File "modules.promise in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 127, in resolve_fn
  File "modules.promise in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 139, in _do_resolve
  File "modules.promise in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 97, in callback_wrapper
  File "git_gutter_handler in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 276, in write_file
  File "git_gutter_handler in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 83, in tmp_file
  File "./python3.3/tempfile.py", line 290, in mkstemp
  File "./python3.3/tempfile.py", line 219, in _mkstemp_inner
OSError: [Errno 24] Too many open files: '/var/folders/fc/w04z5z256yv_gm0tl5qx3mw00000gq/T/git_gutter_lztdph'
OSError [Errno 24] Too many open files
OSError [Errno 24] Too many open files
error: Too many open files
error: Too many open files
OSError [Errno 24] Too many open files
OSError [Errno 24] Too many open files
error: Too many open files
error: Too many open files
```

The file limit on macOS is quite low:

```bash
$ ulimit --file-descriptor-count 
256
```

EDIT: Ok well, I did some more research and it seems my Sublime Text process, and its child process "plugin_host" just happen to have a large number of files open; I'll try to increase my limit

**Comment by deathaxe** [comment]
GitGutter required 2 file descriptors per view. They are needed to write the temporary files, whose pathes are passed to git to compare the view's content against the index. All files are accessed via `with open ... as file` statement to ensure the files are closed after writing.

If an operating system runs out of file descriptors this can't be handled by GitGutter.

In times of _node_ and other heavy scripting engines which may access hundreds or thousands of files at a second a limit of 256 file descriptors seem absolutly outdated and not state of the art.

What I may need to do is catch the exceptions while creating temporary files.
