### ISSUE TITLE
Diff Popup not showing 

### ISSUE THREAD

**Issue by IsmailM** [jisaacks/GitGutter#418]
## Description
For some reason, I don't see the diff popup when hovering over the git gutter (or when selecting `GitGutter: Show Diff Popup` in the command pallete).

## Support Info

- Sublime Text 3126
- Platform: osx
- Arch: x64
- GitGutter 1.7.1
- Install via PC: True
- git version 2.13.0
- mdpopups 1.13.1
- markdown 2.6.6
- pygments 2.1a0
- jinja2 2.8

## Console Output 

```
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin GitGutter.plugin
reloading plugin Material Theme.Icons
reloading plugin Material Theme.MT
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Pretty Ruby.PrettyRubyFormat
reloading plugin Python Pretty Print.PPrint
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SideBarEnhancements.Stats
reloading plugin SublimeLinter-html-tidy.linter
SublimeLinter: htmltidy linter loaded 
reloading plugin SublimeLinter-jshint.linter
SublimeLinter: jshint linter loaded 
reloading plugin SublimeLinter-pep8.linter
SublimeLinter: pep8 linter loaded 
reloading plugin SublimeLinter-pyflakes.linter
SublimeLinter: pyflakes linter loaded 
reloading plugin SublimeLinter-pyyaml.linter
SublimeLinter: pyyaml linter loaded 
reloading plugin SublimeLinter-rubocop.linter
SublimeLinter: rubocop linter loaded 
reloading plugin SublimeLinter-shellcheck.linter
SublimeLinter: shellcheck linter loaded 
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin Minify.Minify
reloading plugin Pretty JSON.PrettyJson
reloading plugin Pretty JSON.PrettyJsonListeners
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: off 
Package Control: Skipping automatic upgrade, last run at 2017-05-30 18:03:15, next run at 2017-05-30 19:03:15 or after
SublimeLinter: pep8 activated: <builtin> 
SublimeLinter: pyflakes activated: <builtin> 
Traceback (most recent call last):
  File "modules.popup.factory in /Users/ismailm/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 46, in <lambda>
  File "modules.popup.factory in /Users/ismailm/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 176, in _show_diff_popup_impl
  File "/Users/ismailm/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/__init__.py", line 466, in get_language_from_view
    keys = set(list(lang_map.keys()) + list(user_map.keys()))
AttributeError: 'NoneType' object has no attribute 'keys'
```

The last 6 lines (from Traceback) are shown when attempting to see the diff popup

**Comment by r-stein** [comment]
Can you please run to check that these calls does not result in `None`:
```py
sublime.load_settings('Preferences.sublime-settings').get('mdpopups.sublime_user_lang_map', {})
```
and 
```py
from mdpopups.st_mapping import lang_map; lang_map
```

**Comment by IsmailM** [comment]
Thanks for the prompt reply 👍 

I ran them in sublime’s console:


```
>>> sublime.load_settings('Preferences.sublime-settings').get('mdpopups.sublime_user_lang_map', {})
>>> 
>>> 
>>> from mdpopups.st_mapping import lang_map; lang_map
{'c': (('c',), ('C++/C',)), 'd': (('d',), ('D/D',)), 'objective-c': (('objective-c', 'objectivec', 'obj-c', 'objc'), ('Objective-C/Objective-C',)), 'diff': (('diff',), ('Diff/Diff',)), 'objective-c++': (('objective-c++', 'objectivec++', 'obj-c++', 'objc++'), ('Objective-C/Objective-C++',)), 'php': (('php', 'php3', 'php4', 'php5'), ('PHP/PHP',)), 's': (('splus', 's', 'r'), ('R/R',)), 'ocaml': (('ocaml',), ('OCaml/OCaml',)), 'matlab': (('matlab', 'octave'), ('Matlab/Matlab',)), 'applescript': (('applescript',), ('AppleScript/AppleScript',)), 'textile': (('textile',), ('Textile/Textile',)), 'clojure': (('clojure', 'clj'), ('Clojure/Clojure',)), 'batch': (('batch', 'bat', 'dosbatch', 'winbatch'), ('Batch File/Batch File',)), 'ruby': (('rb', 'ruby'), ('Ruby/Ruby',)), 'cmake': (('cmake',), ('CMake/CMake',)), 'erlang': (('erlang',), ('Erlang/Erlang',)), 'pascal': (('delphi', 'pas', 'pascal', 'objectpascal'), ('Pascal/Pascal',)), 'scala': (('scala',), ('Scala/Scala',)), 'c#': (('csharp', 'c#'), ('C#/C#',)), 'railsjs': (('js+erb', 'javascript+erb', 'js+ruby', 'javascript+ruby'), ('Rails/JavaScript (Rails)',)), 'tcl': (('tcl',), ('TCL/Tcl',)), 'perl': (('perl', 'pl'), ('Perl/Perl', 'ModernPerl/ModernPerl')), 'xml': (('xml',), ('XML/XML',)), 'java': (('java',), ('Java/Java',)), 'lua': (('lua',), ('Lua/Lua',)), 'html': (('html',), ('HTML/HTML',)), 'markdown': (('markdown', 'md'), ('Markdown/Markdown',)), 'regex': (('regex', 'regexp'), ('Regular Expressions/RegExp',)), 'go': (('go',), ('Go/Go',)), 'css': (('css',), ('CSS/CSS',)), 'yaml': (('yaml',), ('YAML/YAML',)), 'actionscript': (('as', 'actionscript'), ('ActionScript/ActionScript',)), 'haskell': (('haskell', 'hs'), ('Haskell/Haskell',)), 'jsp': (('jsp',), ('Java/Java Server Pages (JSP)',)), 'rst': (('rst', 'rest', 'restructuredtext'), ('RestructuredText/reStructuredText',)), 'groovy': (('groovy',), ('Groovy/Groovy',)), 'json': (('json',), ('JavaScript/JSON', 'JavaScriptNext - ES6 Syntax/JSON (JavaScriptNext)')), 'railshtml': (('rhtml', 'html+erb', 'html+ruby'), ('Rails/HTML (Rails)',)), 'c++': (('c++', 'cpp'), ('C++/C++',)), 'tex': (('tex', 'latex'), ('LaTeX/LaTeX',)), 'python': (('python', 'py'), ('Python/Python', 'MagicPython/grammars/MagicPython')), 'sql': (('sql',), ('SQL/SQL',)), 'lisp': (('common-lisp', 'cl', 'lisp', 'emacs', 'elisp'), ('Lisp/Lisp',)), 'text': (('text',), ('Text/Plain text',)), 'asp': (('asp',), ('ASP/ASP',)), 'javascript': (('javascript', 'js'), ('JavaScript/JavaScript', 'JavaScriptNext - ES6 Syntax/JavaScriptNext')), 'makefile': (('makefile', 'make', 'mf', 'bsdmake'), ('Makefile/Makefile',)), 'bash': (('bash', 'sh', 'ksh', 'shell'), ('ShellScript/Shell-Unix-Generic',))}
```

**Comment by r-stein** [comment]
Open your user Preferences and check that there is no key with the name `mdpopups.sublime_user_lang_map`, i.e. not `"mdpopups.sublime_user_lang_map": null,`.

**Comment by IsmailM** [comment]
nothing like that in my user preference...

**Comment by r-stein** [comment]
Weird, but this this does print `None`?

```py
print(sublime.load_settings('Preferences.sublime-settings').get('mdpopups.sublime_user_lang_map', {}))
```

Then just try to add `"mdpopups.sublime_user_lang_map": {},` to your user preferences (*Preferences > Settings*, right side) at best somewhere at the bottom. Not sure what's the problem, but maybe you have an other package, which sets this preference to `null`.

**Comment by IsmailM** [comment]
In Sublime's Console:
```python
>>> print(sublime.load_settings('Preferences.sublime-settings').get('mdpopups.sublime_user_lang_map', {}))
None
```

Just realized that the popup was working where there was no diff - i.e when adding a few blank lines

Nevertheless, adding `"mdpopups.sublime_user_lang_map": {},` to the user preferences fixed the issue 👍 

Many thanks for your prompt help with this matter

**Comment by r-stein** [comment]
> Just realized that the popup was working where there was no diff - i.e when adding a few blank lines

We only need to call that function to create the syntax highlighting for the text before, so I expected this.

Good that it works now =) I assume you have somewhere in a package a file `Preferences.sublime-settings`, which contains the line `"mdpopups.sublime_user_lang_map": null,` but I don't understand why someone would create such a package :/.
