### ISSUE TITLE
IndexError exception in console

### ISSUE THREAD

**Issue by rwols** [jisaacks/GitGutter#429]
```
Traceback (most recent call last):
  File "modules.handler in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 724, in <lambda>
  File "modules.promise in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 128, in resolve_fn
  File "modules.promise in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 140, in _do_resolve
  File "modules.promise in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 104, in callback_wrapper
  File "modules.promise in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 128, in resolve_fn
  File "modules.promise in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 140, in _do_resolve
  File "modules.promise in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 98, in callback_wrapper
  File "modules.promise in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 128, in resolve_fn
  File "modules.promise in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 140, in _do_resolve
  File "modules.promise in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 98, in callback_wrapper
  File "modules.show_diff in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 76, in _check_ignored_or_untracked
  File "modules.show_diff in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 91, in _update_ui
  File "modules.show_diff in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 185, in _contents_to_regions
  File "modules.show_diff in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 275, in _lines_to_regions
IndexError: list index out of range
```

## Support Info

- Sublime Text 3141
- Platform: osx
- Arch: x64
- GitGutter 1.7.2
- Install via PC: True
- git version 2.11.0 (Apple Git-81)
- mdpopups 2.1.1
- markdown 2.6.6
- pygments 2.1a0
- jinja2 2.8

## Steps to Reproduce Issue

It's hard for me to reproduce this, it seems to be a race condition involving promises. I'll update the issue with reproducible steps when I find it.

**Comment by deathaxe** [comment]
This issue most likely happens, if a changed hunk at the end of a maybe large file is deleted or moved. As GitGutter runs asynchronously, the line mapping being used to translate the diff lines to regions is sometimes no longer up to date.

Maybe need to add some handling to fail silently.
