### ISSUE TITLE
Stopped working after Sublime 3 upgrade to build 3143

### ISSUE THREAD

**Issue by igorescobar** [jisaacks/GitGutter#443]
I've just upgrated Sublime 3 to build 3143 (MacOSX 10.12.6) and GitGutter stoped working after this.

This is what the console outputs after I tried to re-install it:
```
ignored packages updated to: ["GitGutter", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'pygments' is not currently installed; installing...
Package Control: The dependency 'pygments' has successfully been installed or updated
Package Control: The dependency 'python-markdown' is not currently installed; installing...
Package Control: The dependency 'python-markdown' has successfully been installed or updated
Package Control: The dependency 'mdpopups' is not currently installed; installing...
Package Control: The dependency 'mdpopups' has successfully been installed or updated
Package Control: The dependency 'python-jinja2' is not currently installed; installing...
Package Control: The dependency 'python-jinja2' has successfully been installed or updated
Package Control: The dependency 'markupsafe' is not currently installed; installing...
Package Control: The dependency 'markupsafe' has successfully been installed or updated
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin GitGutter.plugin
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "plugin in /Users/igorescobar/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "modules in /Users/igorescobar/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "modules.commands in /Users/igorescobar/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "modules.popup in /Users/igorescobar/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 15, in <module>
AttributeError: 'module' object has no attribute 'version'
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

Ideas?

**Comment by igorescobar** [comment]
After removing the plugin `SublimeFixMacPath` it started to work again.

**Comment by deathaxe** [comment]
Doesn't need to depend on SublimeFixMacPath. I also found all dependencies to fail loading for the first couple of startups. Not sure why.

**Comment by deathaxe** [comment]
In my case `bs4` still resists to load.
