### ISSUE TITLE
Popup font not sans serif any more

### ISSUE THREAD

**Issue by dingo-d** [jisaacks/GitGutter#464]
## Description

Yesterday the GitGutter popup had normal sans serif fonts, and today the fonts are serif and small, the whole popup is weird

<img width="910" alt="screen shot 2017-10-26 at 15 32 55" src="https://user-images.githubusercontent.com/8638515/32055814-2881c0b6-ba63-11e7-8c8c-4bfa7a191d5b.png">

## Support Info

- Sublime Text 3143
- Platform: osx
- Arch: x64
- GitGutter 1.7.8
- Install via PC: True
- git version 2.13.0
- mdpopups 3.0.3
- markdown 2.6.9
- pygments 2.1a0
- jinja2 2.8

**Comment by deathaxe** [comment]
Looks like something causes the default no longer to be applied at all. The button bar normally has a different color than the rest and the toolbar symbols must not be underlined.

The default stylesheet for popups is part of GitGutter.sublime-package named `gitgutter_popup.css`.

Maybe something is overloading the default stylesheet or breaking correct loading.

**Comment by dingo-d** [comment]
Is there any way of knowing what is causing the issue, bar disabling packages one by one until I see the changes?

**Comment by deathaxe** [comment]
GitGutter uses mdpopups for the diff popup. You can look for `gitgutter_popup.css` or check whether a `mdpopups.css` exists in your User package with malformed CSS. You could also have a look to ST's console. Maybe mdpopups complains about something?

GitGutter looks for `gitgutter_popup.css` in the _User_ package, the folder containing the selected gitgutter-theme and _GitGutter_ package itself and merges all of them.

The only known package providing gitgutter-themes is MonokaiPro. Not sure about others.

**Comment by dingo-d** [comment]
I tried searching for those css files but couldn't find them. I looked in the `Library/Application Support/Sublime Text 3` but couldn't find anything...

**Comment by deathaxe** [comment]
Any errors in ST's console?

Could you please do the following steps?

1. add `"mdpopups.debug": 3,` to your Preferences.sublime-settings
2. hover a single changed line once (to keep console output small)
3. Post the console output here?

It should look like:

```
mdpopups: =====CSS=====
mdpopups: 
html {
  --mdpopups-font-mono: "sf mono", Consolas, "Liberation Mono", Menlo, Courier, monospace;
  --mdpopups-admon-fg: var(--foreground);
  --mdpopups-admon-info-fg: var(--foreground);
  --mdpopups-admon-error-fg: var(--foreground);
  --mdpopups-admon-warning-fg: var(--foreground);
  --mdpopups-admon-success-fg: var(--foreground);
  --mdpopups-admon-bg: var(--background);
  --mdpopups-admon-info-bg: var(--background);
  --mdpopups-admon-error-bg: var(--background);
  --mdpopups-admon-warning-bg: var(--background);
  --mdpopups-admon-success-bg: var(--background);
  --mdpopups-admon-accent: color(var(--background) blend(var(--foreground) 50%));
  --mdpopups-admon-title-fg:  var(--foreground);
  --mdpopups-admon-info-title-fg:  var(--foreground);
  --mdpopups-admon-error-title-fg:  var(--foreground);
  --mdpopups-admon-warning-title-fg:  var(--foreground);
  --mdpopups-admon-success-title-fg:  var(--foreground);
  --mdpopups-admon-info-accent: color(var(--background) blend(var(--bluish) 50%));
  --mdpopups-admon-error-accent: color(var(--background) blend(var(--redish) 50%));
  --mdpopups-admon-warning-accent: color(var(--background) blend(var(--orangish) 50%));
  --mdpopups-admon-success-accent: color(var(--background) blend(var(--greenish) 50%));
  --mdpopups-kbd-fg: var(--background);
  --mdpopups-kbd-bg: var(--foreground);
}
html.light {
  --mdpopups-hr: color(var(--foreground) blend(white 80%));
  --mdpopups-kbd-border: color(var(--foreground) blend(white 80%));
  --mdpopups-hl-border: color(var(--background) blend(black 90%));
  --mdpopups-hl-bg: color(var(--background) blend(black 98%));
}
html.dark {
  --mdpopups-hr: color(var(--foreground) blend(black 80%));
  --mdpopups-kbd-border: color(var(--foreground) blend(black 80%));
  --mdpopups-hl-border: color(var(--background) blend(white 90%));
  --mdpopups-hl-bg: color(var(--background) blend(white 98%));
}
html, body { padding: 0; margin: 0; }
div.mdpopups {
  display: block;
  margin: 0;
  padding: 0;
  font-size: 1rem;
  line-height: 1.1rem;
}
.mdpopups .highlight,
.mdpopups code,
.mdpopups var,
.mdpopups tt {
  font-family: var(--mdpopups-font-mono);
}
.mdpopups div { display: block; }

.mdpopups h1 { font-size: 1.5rem; }
.mdpopups h2 { font-size: 1.4rem; }
.mdpopups h3 { font-size: 1.3rem; }
.mdpopups h4 { font-size: 1.2rem; }
.mdpopups h5 { font-size: 1.1rem; }
.mdpopups h6 { font-size: 1rem; }
.mdpopups h1, .mdpopups h2, .mdpopups h3, .mdpopups h4, .mdpopups h5, .mdpopups h6 {
  margin-top: 0.2rem;
  margin-bottom: 0.2rem;
}

.mdpopups blockquote { display: block; font-style: italic; }

.mdpopups hr {
  display: block;
  border-color: var(--mdpopups-hr);
  border-style: solid;
  border-width: 0 0 1px 0;
  margin-top: 1rem;
  margin-bottom: 1rem;
}

.mdpopups dl { display: block; }
.mdpopups dt {
  display: block;
  font-style: italic;
  font-weight: bold;
  margin-bottom: 0.5rem;
}
.mdpopups dd {
  display: block;
  margin-left: 1.5rem;
  margin-bottom: 0.5rem;
}

.mdpopups pre { display: block; }

.mdpopups blockquote, .mdpopups ol, .mdpopups ul, .mdpopups dl, .mdpopups p {
  padding: 0;
  margin-top: 0;
  margin-bottom: 0.5rem;
  margin-left: 0;
  margin-right: 0;
}
.mdpopups ul, .mdpopups ol { padding-left: 2rem; }

.mdpopups kbd {
  display: inline;
  font-size: 0.9rem;
  padding: 0.05rem 0.25rem;
  border-radius: 0.25rem;
  background-color: var(--mdpopups-kbd-bg);
  color: var(--mdpopups-kbd-fg);
  border: 1px solid var(--mdpopups-kbd-border);
}

.mdpopups .admonition {
  display: block;
  padding: 0 0.5rem 0.5rem 0.5rem;
  border-radius: 0.25rem;
  margin-bottom: 0.5rem;
  background-color: var(--mdpopups-admon-bg);
  color: var(--mdpopups-admon-fg);
  border: 1px solid var(--mdpopups-admon-accent);
}
.mdpopups .admonition-title {
  font-weight: 600;
  font-size: 1.1rem;
  margin: 0 -0.5rem 0.5rem -0.5rem;
  padding: 0.1rem 0.5rem 0.1rem 0.5rem;
  border-top-left-radius: 0.25rem;
  border-top-right-radius: 0.25rem;
  color:  var(--mdpopups-admon-title-fg);
  background-color: var(--mdpopups-admon-accent);
}

.mdpopups .admonition.panel-success .admonition-title {
  color: var(--mdpopups-admon-success-title-fg);
  background-color: var(--mdpopups-admon-success-accent);
}
.mdpopups .admonition.panel-success {
  color:  var(--mdpopups-admon-success-fg);
  background-color: var(--mdpopups-admon-success-bg);
  border-color: var(--mdpopups-admon-success-accent);
}
.mdpopups .admonition.panel-warning .admonition-title {
  color: var(--mdpopups-admon-warning-title-fg);
  background-color: var(--mdpopups-admon-warning-accent);
}
.mdpopups .admonition.panel-warning {
  color:  var(--mdpopups-admon-warning-fg);
  background-color: var(--mdpopups-admon-warning-bg);
  border-color: var(--mdpopups-admon-warning-accent);
}
.mdpopups .admonition.panel-error .admonition-title {
  color: var(--mdpopups-admon-error-title-fg);
  background-color: var(--mdpopups-admon-error-accent);
}
.mdpopups .admonition.panel-error {
  color:  var(--mdpopups-admon-error-fg);
  background-color: var(--mdpopups-admon-error-bg);
  border-color: var(--mdpopups-admon-error-accent);
}
.mdpopups .admonition.panel-info .admonition-title {
  color: var(--mdpopups-admon-info-title-fg);
  background-color: var(--mdpopups-admon-info-accent);
}
.mdpopups .admonition.panel-info {
  color:  var(--mdpopups-admon-info-fg);
  background-color: var(--mdpopups-admon-info-bg);
  border-color: var(--mdpopups-admon-info-accent);
}
.mdpopups .highlight {
  border: 1px solid var(--mdpopups-hl-border);
  border-radius: 0.25rem;
  font-size: 0.9rem;
  background-color: var(--mdpopups-hl-bg);
}
.mdpopups div.highlight,
.mdpopups pre.highlight {
  padding: 0.5rem;
  margin-bottom: 0.5rem;
  font-size: 1rem;
}
.mdpopups code.highlight{
  padding: 0.05rem 0.25rem;
}




html.dark {
    --mdpopups-hl-bg: color(var(--background) blend(white 95%));
    --diffpopup-tb-bg: color(var(--mdpopups-hl-bg) blend(white 95%));
    --diffpopup-ins-bg: color(green blend(black 60%));
    --diffpopup-ins-fg: color(green blend(white 40%));
    --diffpopup-del-bg: color(red blend(black 60%));
    --diffpopup-del-fg: color(red blend(white 40%));
    --diffpopup-chg-ins-bg: color(#769908 blend(black 95%));
    --diffpopup-chg-ins-fg: color(#769908 blend(white 20%));
    --diffpopup-chg-del-bg: color(orangered blend(black 80%));
    --diffpopup-chg-del-fg: color(orangered blend(white 40%));
}

html.light {
    --mdpopups-hl-bg: color(var(--background) blend(black 95%));
    --diffpopup-tb-bg: color(var(--mdpopups-hl-bg) blend(black 91%));
    --diffpopup-ins-bg: color(green blend(white 25%));
    --diffpopup-ins-fg: color(green blend(black 80%));
    --diffpopup-del-bg: color(red blend(white 25%));
    --diffpopup-del-fg: color(red blend(black 80%));
    --diffpopup-chg-ins-bg: color(#93921b blend(white 20%));
    --diffpopup-chg-ins-fg: color(#93921b blend(black 85%)); 
    --diffpopup-chg-del-bg: color(orangered blend(white 20%));
    --diffpopup-chg-del-fg: color(orangered blend(black 85%));
}


div.git-gutter {
    margin: 0;
    padding: 0;
}


.git-gutter div.toolbar {
    background-color: var(--diffpopup-tb-bg);
    color: color(var(--foreground) blend(var(--diffpopup-tb-bg) 30%));
    margin: 0;
    padding: 0.0rem 0.4rem 0.2rem 0.4em;
}


.git-gutter div.toolbar symbol {
    font-family: "Roboto Mono", "Segoe UI", monospace;
    font-size: 1.2rem;
    margin: 0;
    padding: 0.0rem 0.1rem 0.0rem 0.1em;
}


.git-gutter a {
    color: var(--foreground);
    text-decoration: bold;
}


.git-gutter div.highlight {
    font-family: "sf mono", "Roboto Mono", "Liberation Mono", Menlo, Courier, monospace;
    border-style: none;
    line-height: 1.3rem;
    margin: 0;
    padding: 0.7rem 0.7rem 0.6rem 0.7rem;
}


.git-gutter .highlight p {
    margin: 0;
}




.git-gutter .hi-ins {
    color: var(--diffpopup-ins-fg);
    background-color: var(--diffpopup-ins-bg);
}


.git-gutter .hi-del {
    color: var(--diffpopup-del-fg);
    background-color: var(--diffpopup-del-bg);
}


.git-gutter .hi-chg-ins {
    color: var(--diffpopup-chg-ins-fg);
    background-color: var(--diffpopup-chg-ins-bg);
}


.git-gutter .hi-chg-del {
    color: var(--diffpopup-chg-del-fg);
    background-color: var(--diffpopup-chg-del-bg);
}



.lsp_popup .highlight {
  border: 1px solid var(--mdpopups-hl-border);
}

.lsp_popup p,
.lsp_popup li
{
    font-family: "Roboto Mono";
}
mdpopups: =====HTML OUTPUT=====
mdpopups: 
<div class="toolbar">
 <a href="hide">
  <symbol>
   ×
  </symbol>
 </a>
 <symbol>
  ⤒
 </symbol>
 <symbol>
  ↑
 </symbol>
 <symbol>
  ↓
 </symbol>
 <a href="enable_hl_diff">
  <symbol>
   ≈
  </symbol>
 </a>
 <a href="copy">
  <symbol>
   ⎘
  </symbol>
 </a>
 <a href="revert">
  <symbol>
   ⟲
  </symbol>
 </a>
</div>
<div class="highlight">
 <pre><span style="color: #75715e;">#</span><span style="color: #75715e;"> to internal structure changes.</span><br/></pre>
</div>

```

**Comment by dingo-d** [comment]
I am getting this:

```sh
mdpopups: Failed to get Sublime highlighter object!
mdpopups: Traceback (most recent call last):
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/__init__.py", line 155, in _get_sublime_highlighter
    obj = SublimeHighlight(scheme)
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_code_highlight.py", line 52, in __init__
    self.csm = ColorSchemeMatcher(scheme)
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_color_scheme_matcher.py", line 347, in __init__
    self.merge_overrides()
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_color_scheme_matcher.py", line 453, in parse_scheme
    name = item.get('name', '')
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_color_scheme_matcher.py", line 173, in translate_color
    if m is not None:
AttributeError: 'NoneType' object has no attribute 'groupdict'

mdpopups: Failed to highlight code!
mdpopups: Traceback (most recent call last):
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/__init__.py", line 522, in syntax_highlight
    code = highlighter.syntax_highlight(
AttributeError: 'NoneType' object has no attribute 'syntax_highlight'

mdpopups: Failed to convert/retrieve scheme to CSS!
mdpopups: Traceback (most recent call last):
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/__init__.py", line 187, in _get_scheme
    obj = SchemeTemplate(scheme)
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_scheme_template.py", line 71, in __init__
    self.setup()
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_scheme_template.py", line 178, in setup
    self.legacy_parse_global()
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_scheme_template.py", line 104, in legacy_parse_global
    self.csm = ColorSchemeMatcher(self.scheme_file)
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_color_scheme_matcher.py", line 347, in __init__
    self.merge_overrides()
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_color_scheme_matcher.py", line 453, in parse_scheme
    name = item.get('name', '')
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_color_scheme_matcher.py", line 173, in translate_color
    if m is not None:
AttributeError: 'NoneType' object has no attribute 'groupdict'

mdpopups: =====CSS=====
mdpopups: 
mdpopups: =====HTML OUTPUT=====
mdpopups: 
<div class="toolbar"><a href="hide"><symbol>×</symbol></a> <symbol>⤒</symbol> <symbol>↑</symbol> <symbol>↓</symbol> <a href="enable_hl_diff"><symbol>≈</symbol></a> <a href="copy"><symbol>⎘</symbol></a> <a href="revert"><symbol>⟲</symbol></a></div>let isSearchLoading = false; // This should be added along with the stopping button.
mdpopups: Failed to get Sublime highlighter object!
mdpopups: Traceback (most recent call last):
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/__init__.py", line 155, in _get_sublime_highlighter
    obj = SublimeHighlight(scheme)
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_code_highlight.py", line 52, in __init__
    self.csm = ColorSchemeMatcher(scheme)
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_color_scheme_matcher.py", line 347, in __init__
    self.merge_overrides()
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_color_scheme_matcher.py", line 453, in parse_scheme
    name = item.get('name', '')
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_color_scheme_matcher.py", line 173, in translate_color
    if m is not None:
AttributeError: 'NoneType' object has no attribute 'groupdict'

mdpopups: Failed to highlight code!
mdpopups: Traceback (most recent call last):
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/__init__.py", line 522, in syntax_highlight
    code = highlighter.syntax_highlight(
AttributeError: 'NoneType' object has no attribute 'syntax_highlight'

mdpopups: Failed to convert/retrieve scheme to CSS!
mdpopups: Traceback (most recent call last):
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/__init__.py", line 187, in _get_scheme
    obj = SchemeTemplate(scheme)
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_scheme_template.py", line 71, in __init__
    self.setup()
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_scheme_template.py", line 178, in setup
    self.legacy_parse_global()
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_scheme_template.py", line 104, in legacy_parse_global
    self.csm = ColorSchemeMatcher(self.scheme_file)
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_color_scheme_matcher.py", line 347, in __init__
    self.merge_overrides()
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_color_scheme_matcher.py", line 453, in parse_scheme
    name = item.get('name', '')
  File "/Users/infinum/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_color_scheme_matcher.py", line 173, in translate_color
    if m is not None:
AttributeError: 'NoneType' object has no attribute 'groupdict'

mdpopups: =====CSS=====
mdpopups: 
mdpopups: =====HTML OUTPUT=====
mdpopups: 
<div class="toolbar"><a href="hide"><symbol>×</symbol></a> <symbol>⤒</symbol> <symbol>↑</symbol> <symbol>↓</symbol> <a href="enable_hl_diff"><symbol>≈</symbol></a> <a href="copy"><symbol>⎘</symbol></a> <a href="revert"><symbol>⟲</symbol></a></div>let isSearchLoading = false; // This should be added along with the stopping button.
```

From what I can tell the relevant issue is `mdpopups: Failed to convert/retrieve scheme to CSS!`

**Comment by deathaxe** [comment]
It's mdpopups which fails to parse your color scheme. It fails to read the `foreground` color of an element, which causes the tracebacks. We could ask @facelessuser whether some recent changes may be responsible for that issues. I downloaded Material Theme, activated each of the provided color schemes without encountering any issues.

Did any plugin like SublimeLinter create a patched (hacked) color scheme which might be broken? You can find it out by checking the `"color_scheme"` setting in your Preferences. If yes, a copy of that file might help to find the reason for the parse error.

Changing the color scheme to a safe default value and deleting (moving away) the patched version should help.

**Comment by dingo-d** [comment]
Could be that. I checked today and it seems like the issue was gone. Thanks for the help.

**Comment by facelessuser** [comment]
Yeah, that was some recent fixes with the new paint logic. It's likey you picked those up and that's why your issue went away.
