### ISSUE TITLE
with some of my .js file 'UnicodeDecodeError' occurs

### ISSUE THREAD

**Issue by muzehyun** [jisaacks/GitGutter#53]
Traceback (most recent call last):
  File "./sublime_plugin.py", line 339, in run_
  File "./git_gutter.py", line 32, in run
  File "./view_collection.py", line 36, in diff
  File "./git_gutter_handler.py", line 151, in diff
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x96 in position 14146: invalid start byte

Traceback (most recent call last):
  File "./sublime_plugin.py", line 339, in run_
  File "./git_gutter.py", line 32, in run
  File "./view_collection.py", line 36, in diff
  File "./git_gutter_handler.py", line 149, in diff
LookupError: unknown encoding: Western(Windows1252)

**Comment by FichteFoll** [comment]
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 535, in run_
    return self.run()
  File "git_gutter in C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package", line 33, in run
  File "view_collection in C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package", line 51, in diff
  File "git_gutter_handler in C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package", line 161, in diff
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 384: invalid start byte
Traceback (most recent call last):
  File "git_gutter_handler in C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package", line 159, in diff
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 384: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 535, in run_
    return self.run()
  File "git_gutter in C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package", line 33, in run
  File "view_collection in C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package", line 51, in diff
  File "git_gutter_handler in C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package", line 161, in diff
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 384: invalid start byte
```

File: https://dl.dropboxusercontent.com/u/23263478/YAML%201.2.sublime-syntax

Copying from the file and pasting to another one did not result in the above exception - neither did reverting to my latest commit. Interestingly, there doesn't actually appear to be a 0x93 byte in that file:
```py
>>> s = view.substr(sublime.Region(0, view.size()))
>>> "\x93" in s
False
>>> b"\x93" in s.encode("utf8")
False
```
```py
>>> f = open(view.file_name(), 'br'); s = f.read(); f.close(); b"\x93" in s
False
```

**Comment by deathaxe** [comment]
Decode exceptions are handled.

In worst case empty output will be returned.
