### ISSUE TITLE
Sublime Text 4 support, please

### ISSUE THREAD

**Issue by kirylpl** [jisaacks/GitGutter#566]
Subject.

**Comment by michaelblyons** [comment]
What, specifically, do you feel is missing? I'm running GG in ST4 just fine.

**Comment by matteolaltrelli** [comment]
In Sublime Text 4113 with gitgutter 1.11.6 the function show_line_annotation don't show information about the author of commit

**Comment by deathaxe** [comment]
ST4 is fully supported by GitGutter.

Line annotations use ST4's new annotation API. Works fine here on Win10 with git 2.33

![grafik](https://user-images.githubusercontent.com/16542113/135118377-5f475f8c-4d7d-4591-9467-a59ee6768648.png)

Note: It doesn't display anything on modified lines.

**Comment by tmanderson** [comment]
I am seeing the same error with the annotations. The error:

```
TypeError: render() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "~/Library/Application Support/Sublime Text/Installed Packages/GitGutter.sublime-package/modules/tasks.py", line 65, in run
    task.run()
  File "~/Library/Application Support/Sublime Text/Installed Packages/GitGutter.sublime-package/modules/tasks.py", line 23, in run
    self.target(*self.args, **self.kwargs)
  File "~/Library/Application Support/Sublime Text/Installed Packages/GitGutter.sublime-package/modules/handler.py", line 809, in task_fn
    return resolve(chunk.decode('utf-8').strip())
  File "~/Library/Application Support/Sublime Text/Installed Packages/GitGutter.sublime-package/modules/promise.py", line 137, in resolve_fn
    self._do_resolve(new_value)
  File "~/Library/Application Support/Sublime Text/Installed Packages/GitGutter.sublime-package/modules/promise.py", line 149, in _do_resolve
    callback(new_value)
  File "~/Library/Application Support/Sublime Text/Installed Packages/GitGutter.sublime-package/modules/promise.py", line 107, in callback_wrapper
    result = callback(resolve_value)
  File "~/Library/Application Support/Sublime Text/Installed Packages/GitGutter.sublime-package/modules/blame.py", line 101, in _render_blame
    git_gutter.line_annotation.update(row, **blame)
  File "~/Library/Application Support/Sublime Text/Installed Packages/GitGutter.sublime-package/modules/annotation.py", line 244, in update
    text = self.template.render(kwargs)
TypeError: render() takes 1 positional argument but 2 were given
```

This must have broken relatively recently (within the past week or so) as everything, including the annotations, was working just fine in ST4.

**Comment by deathaxe** [comment]
This indicates python-jinja2 dependency to be missing.

**Comment by tmanderson** [comment]
@deathaxe thanks for the quick reply. Any idea how to go about fixing this? Is this something with Sublime Text's own bundled dependencies? Or something with the gitgutter package itself? Or is it something I can resolve manually?

**Comment by AlexVPopov** [comment]
I can confirm this is broken for me, too, with the same error message, as @tmanderson showed. I'm running same ST4 build + macOS version.

**Comment by matteolaltrelli** [comment]
@danhper  in my ~/Library/Application Support/Sublime Text 3/Packages python-jinja2 appears to be installed correctly.
Sublime Text 4113 + gitgutter 1.11.6 + macOS 10.14.6

**Comment by deathaxe** [comment]
GitGutter uses jinja2 by default to be able to customize those annotations as well as statusbar messages via Preferences. If jinja is not accessible it falls back to some basic/static templating classes. The one for annotations suffers from a typo.

I'll need to look into why jinja is not loaded for some of you. It's declared as dependency by Gitgutter and therefore should be installed automatically by Package Control.

Maybe invoking `Package Control: Satisfy Dependencies` manually already resolves the problem?

If the `python-jinja2` folder is present, you should be able to run `import jinja2` via ST's console (if python3.3 environment is selected). If not, you could check whether `0_package_control_loader` exists in `ignored_packages`. PC sometimes adds there forever.

**Comment by deathaxe** [comment]
It turned out `markupsafe` is required by `python-jinja2`. Should start working with 1.11.7 again.

**Comment by tmanderson** [comment]
Great, successfully upgraded the package via "Package Control: Upgrade/Overwrite All Packages" and annotations are working again! Thank you for addressing this so quickly 👍

**Comment by matteolaltrelli** [comment]
@deathaxe 
thanks for your great work
