### ISSUE TITLE
1.11.8 can not work in ST4 with win11.

### ISSUE THREAD

**Issue by jokervTv** [jisaacks/GitGutter#575]
Update to 1.11.8, can not work!

---

and the log in the console:

```log
reloading plugin GitGutter.plugin
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 325, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 808, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\yongp\AppData\Roaming\Sublime Text\Installed Packages\GitGutter.sublime-package\plugin.py", line 21, in <module>
  File "C:\Users\yongp\AppData\Roaming\Sublime Text\Installed Packages\GitGutter.sublime-package\modules/__init__.py", line 7, in <module>
  File "C:\Users\yongp\AppData\Roaming\Sublime Text\Installed Packages\GitGutter.sublime-package\modules/commands.py", line 12, in <module>
  File "C:\Users\yongp\AppData\Roaming\Sublime Text\Installed Packages\GitGutter.sublime-package\modules/popup/__init__.py", line 9, in <module>
AttributeError: module 'mdpopups' has no attribute 'version'
```

and my PC:

- sublime text 4 4143
- windows 11 22H2

Thank you for your work and have a good day ~

**Comment by cwitting** [comment]
Same issue for me on Ubuntu 16.04.

**Comment by deathaxe** [comment]
Sublime Merge again staged/committed more than I wanted. Hence pushing a .python-version which tells ST to run GitGutter via pythopn 3.8 plugin host, which current release of mdpopups is not prepared for.

_It's because me running all plugins on python 3.8 with Package Control 4.0-dev, already._

Should be fixed by GitGutter 1.11.9

**Comment by AbhishekJadav1998** [comment]
@jokervTv @cwitting try installing gitgutter 1.11.7, uninstall 1.11.7 and then install 1.11.8. For some reason it worked in my case.
I think the issue related for Python 3.8 in some or the other way
cc - @jisaacks @deathaxe

**Comment by AbhishekJadav1998** [comment]
@deathaxe Thank you for Quick Fix. 🙌🏽🙌🏽

**Comment by jokervTv** [comment]
Thanks for the quick fix
