### ISSUE TITLE
GitGutter is throwing errors related to mdpopups and not working

### ISSUE THREAD

**Issue by AbhishekJadav1998** [jisaacks/GitGutter#576]
## Description

I've Installed sublime text 3 and GitGutter. Restarted Sublime but package is not working.
On Sublime terminal I am getting `AttributeError: module 'mdpopups' has no attribute 'version'`
Below is the entire stacktrace
```
environment variables loaded using: /bin/zsh -l
reloading python 3.3 plugin 0_package_control_loader.00-package_control
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading python 3.3 plugin 0_package_control_loader.50-markupsafe
reloading plugin Default.block
reloading plugin Default.colors
reloading python 3.3 plugin 0_package_control_loader.51-python-jinja2
reloading python 3.3 plugin 0_package_control_loader.55-mdpopups
reloading python 3.3 plugin Babel.plugin
reloading python 3.3 plugin Git blame.boot
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading python 3.3 plugin Git.git_commands
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading python 3.3 plugin Package Control.1_reloader
reloading plugin Default.install_package_control
reloading python 3.3 plugin Package Control.2_bootstrap
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin Emmet.main
reloading plugin GitGutter.plugin
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 325, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 808, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/edcast/Library/Application Support/Sublime Text/Packages/GitGutter/plugin.py", line 21, in <module>
    from .modules import *
  File "/Users/edcast/Library/Application Support/Sublime Text/Packages/GitGutter/modules/__init__.py", line 7, in <module>
    from .commands import GitGutterBlameCommand
  File "/Users/edcast/Library/Application Support/Sublime Text/Packages/GitGutter/modules/commands.py", line 12, in <module>
    from . import popup
  File "/Users/edcast/Library/Application Support/Sublime Text/Packages/GitGutter/modules/popup/__init__.py", line 9, in <module>
    if mdpopups.version() < (2, 0, 0):
AttributeError: module 'mdpopups' has no attribute 'version'
reloading plugin GitGutter.release
reloading python 3.3 plugin Package Control.Package Control
reloading python 3.3 plugin SublimeFixMacPath.FixPath
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2023-01-02 22:12:21, next run at 2023-01-02 23:12:21 or after
```

Attachment
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/36496890/210260342-7499ac98-6887-4a38-82f7-b7b705bb7e96.png">

`mdpopups` package was installed after installing GitGutter as it is dependency of package.
I tried installing GitGutter via **Package Control** and also via **Github clone** but problem persists.

My Machine
- MacOS 13.1
- Sublime Text Build 4143
- GitGutter 1.11.8

@jisaacks  Is there anything which i am missing??

**Comment by michaelblyons** [comment]
Duplicate of #575

**Comment by AbhishekJadav1998** [comment]
Apologies. Closing this issue.
Also, Problem resolved. I installed GitGutter pervious version i.e 1.11.7 and it worked fine. Then removed 1.11.7 and installed 1.11.8 and it is working fine.
