### ISSUE TITLE
ZipImportError: bad local file header

### ISSUE THREAD

**Issue by enzy** [jisaacks/GitGutter#81]
From ST3 (3022) console:

```
reloading plugin GitGutter.git_gutter
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 70, in reload_plugin
    m = imp.reload(m)
  File "X/imp.py", line 252, in reload
zipimport.ZipImportError: bad local file header in C:\Users\Enzy\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package
reloading plugin GitGutter.git_gutter_change
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 70, in reload_plugin
    m = imp.reload(m)
  File "X/imp.py", line 252, in reload
zipimport.ZipImportError: bad local file header in C:\Users\Enzy\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package
reloading plugin GitGutter.git_gutter_events
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 70, in reload_plugin
    m = imp.reload(m)
  File "X/imp.py", line 252, in reload
zipimport.ZipImportError: bad local file header in C:\Users\Enzy\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package
reloading plugin GitGutter.git_gutter_handler
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 70, in reload_plugin
    m = imp.reload(m)
  File "X/imp.py", line 252, in reload
zipimport.ZipImportError: bad local file header in C:\Users\Enzy\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package
reloading plugin GitGutter.git_helper
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 70, in reload_plugin
    m = imp.reload(m)
  File "X/imp.py", line 252, in reload
zipimport.ZipImportError: bad local file header in C:\Users\Enzy\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package
reloading Packages/GitGutter/GitGutter.sublime-settings
reloading plugin GitGutter.view_collection
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 70, in reload_plugin
    m = imp.reload(m)
  File "X/imp.py", line 252, in reload
zipimport.ZipImportError: bad local file header in C:\Users\Enzy\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package
```

**Comment by rchl** [comment]
Can't do much about it if it doesn't happen anymore and there are no repro steps. Closing.
